// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using Parcial2024.Data;

#nullable disable

namespace Parcial2024.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20241005021556_AddMonedaRecibidaToRemesa")]
    partial class AddMonedaRecibidaToRemesa
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.8")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("Parcial2024.Models.Remesa", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Destinatario")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("EstadoTransaccion")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("MonedaEnviada")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("MonedaRecibida")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<decimal>("MontoEnviado")
                        .HasColumnType("numeric");

                    b.Property<decimal>("MontoFinal")
                        .HasColumnType("numeric");

                    b.Property<string>("PaisDestino")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("PaisOrigen")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Remitente")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<decimal>("TasaCambio")
                        .HasColumnType("numeric");

                    b.HasKey("Id");

                    b.ToTable("Remesas");
                });
#pragma warning restore 612, 618
        }
    }
}
